### ISSUE TITLE
Does not account for level up screens/"+1 monkey money"

### ISSUE THREAD

**Issue by DereC4** [gavboi/btd6-farming#20]
In the event of a level up, the hotkey script seems to freeze up and not do anything anymore

**Comment by gavboi** [comment]
unfortunately I have gotten to a relatively high level in testing this during development so this will be difficult for me to test but I will try

**Comment by DereC4** [comment]
😭 I'll keep testing, I feel like sometimes it works and sometimes not. Maybe make it so that it clicks every few times when the game is running to account for the level up notification?

**Comment by gavboi** [comment]
> Maybe make it so that it clicks every few times when the game is running to account for the level up notification?

This was how it originally worked, but if you wanted to move your mouse at all to check something it would cause issues. Definitely could add it back as a configuration option, might do that in the future just to have as an option.

> ... I feel like sometimes it works and sometimes not.

__Idea 1: change color match leniency__
Around line 145, simply change the value of `tolerance` in the `nearColor` function (currently is 5). Higher values will have less false negatives, but more false positives. This is probably something you can try now if you're interested, I'll probably mess about with it a bit myself to see if there's a higher value that works everywhere else.

__Idea 2: change detection target__
Currently the level up is detected via the left side of the banner under the star in the pop-up. It was selected because it appears over the very middle of the map, where there are no bloons. As the whole pop-up is red/yellow/white which bloons are as well, I wanted to avoid false positives. The issue with that, I think, is that the whole thing is a gradient so color changes quickly over short distances. The rest of the buttons appear to be gradients as well, which is why I'm a bit confused as to why it's inconsistent, but it is what it is. If the issue is the gradient, I'm going to work on a change that detects the monkey appearing in the bottom left instead as it looks a lot more homogenous, and that should fix it. 
![image](https://github.com/user-attachments/assets/d48c7d44-3fd5-4a32-a692-ae765c7a2f95)

It is also possible that they updated the screen and it no longer looks exactly the same, which will probably be awhile before I can look into myself 😅

**Comment by gavboi** [comment]
@DereC4 [new branch](https://github.com/gavboi/btd6-farming/tree/20-level-up-screens) has changes I discussed above; new testing position, and twice as lenient with colour detection (which still seems to work with everything else). 

Edit: this new method works for me
![image](https://github.com/user-attachments/assets/69dbcc47-eb9d-491e-9a36-d0f79052480b)

**Comment by DereC4** [comment]
will the new update from this week affect this plugin?

**Comment by gavboi** [comment]
@DereC4 after merging the fix for this issue, [I added in the new monkey tower](https://github.com/gavboi/btd6-farming/pull/22) and did some basic testing to make sure nothing was obviously broken. 

> will the new update from this week affect this plugin?

If you are not using the new monkey, everything should work as it did before. If you want to use the new monkey, update to latest master and some instructions are in the [readme](https://github.com/gavboi/btd6-farming/blob/main/README.md).

**Comment by DereC4** [comment]
given the precense of water platforms on the Infernal map, is it possible to add the water monkeys to the list so we can build up paragon xp?

**Comment by gavboi** [comment]
> given the precense of water platforms on the Infernal map, is it possible to add the water monkeys to the list so we can build up paragon xp?

@DereC4 In theory, yes, it is mentioned in this issue: https://github.com/gavboi/btd6-farming/issues/4. Haven't gotten around to it though, no planned date to work on it yet either.
